# Generated by Django 5.0.6 on 2024-06-12 15:41

from django.db import migrations
from django.contrib.auth.models import Group, Permission


class Migration(migrations.Migration):

    def apply_migration(apps, schema_editor):
        admin_group, created = Group.objects.get_or_create(name='admin')

    def revert_migration(apps, schema_editor):
        admin_group = Group.objects.get(name='admin')
        admin_group.delete()
        pass

    dependencies = [
        ('nucommerce', '0003_variant'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
